#!/usr/bin/env bash

docker run -it --rm -u 1000 \
  -w /var/maven/src \
  -v "$PWD":/var/maven/src \
  -v "$HOME/.m2":/var/maven/.m2 \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  maven:3-openjdk-8-slim mvn -Duser.home=/var/maven "$@"